import { Geist_Mono, Inter, Poppins, Fredoka } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/AOC/Provider";
import { ToastContainer } from 'react-toastify';
import { Bounce } from "react-toastify";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fredoka",
  subsets: ["latin"],
});



export const metadata = {
  title: "Split Buddy",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${fredoka.variable} antialiased`}
      >
        <Toaster  
        position="top-center"
         richColors
         toastOptions={{
          classNames : {
            title : 'text-md'
          }
         }}
        />
        <Provider>
          <Navbar />
          {children}
        </Provider>

      </body>
    </html>
  );
}
